//! VPN config generation helpers.
//! Generates ready-to-use client config files for OpenVPN and WireGuard.
//! The user must supply their own server address; cert/key slots are marked clearly.

use std::{fs, net::SocketAddr, path::PathBuf};
use anyhow::{bail, Result};

// ── OpenVPN ──────────────────────────────────────────────────────────────────

pub struct OpenVpnConfig {
    pub server:   String,
    pub port:     u16,
    pub proto:    &'static str, // "udp" | "tcp"
    pub out_path: PathBuf,
}

impl OpenVpnConfig {
    pub fn write(&self) -> Result<()> {
        let config = format!(r#"# Generated by freedomnet — fill in <CA_CERT>, <CLIENT_CERT>, <CLIENT_KEY>
client
dev tun
proto {proto}
remote {server} {port}
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-GCM
auth SHA256
tls-client
tls-version-min 1.2
verb 3

# --- Paste your CA certificate between these tags ---
<ca>
# (paste CA certificate here)
</ca>

# --- Paste your client certificate ---
<cert>
# (paste client certificate here)
</cert>

# --- Paste your client private key ---
<key>
# (paste private key here)
</key>
"#,
            proto  = self.proto,
            server = self.server,
            port   = self.port,
        );

        fs::write(&self.out_path, config)?;
        println!("OpenVPN config written to: {}", self.out_path.display());
        println!();
        println!("Next steps:");
        println!("  1. Open the .ovpn file and paste your CA cert, client cert, and private key.");
        println!("  2. Install OpenVPN client (https://openvpn.net/client/)");
        println!("  3. Import the .ovpn file into the client and connect.");
        Ok(())
    }
}

// ── WireGuard ─────────────────────────────────────────────────────────────────

pub struct WireGuardConfig {
    pub server_endpoint: String, // "host:port"
    pub server_pubkey:   String,
    pub client_address:  String, // e.g. "10.0.0.2/32"
    pub dns:             String,
    pub out_path:        PathBuf,
}

impl WireGuardConfig {
    pub fn write(&self) -> Result<()> {
        // Validate server_endpoint is parseable
        if let Err(_) = self.server_endpoint.parse::<SocketAddr>() {
            // might be hostname:port — just warn
            eprintln!("Warning: server endpoint '{}' could not be parsed as IP:port (hostname is OK)", self.server_endpoint);
        }

        let config = format!(r#"# Generated by freedomnet
# Run `wg genkey | tee privatekey | wg pubkey > publickey` to generate keys
# Then give your PUBLIC key to the server admin so they can add a Peer entry

[Interface]
# Paste your private key here (from `wg genkey`)
PrivateKey = <YOUR_PRIVATE_KEY>
Address    = {client_addr}
DNS        = {dns}

[Peer]
PublicKey  = {server_pubkey}
Endpoint   = {endpoint}
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
"#,
            client_addr  = self.client_address,
            dns          = self.dns,
            server_pubkey = self.server_pubkey,
            endpoint     = self.server_endpoint,
        );

        fs::write(&self.out_path, config)?;
        println!("WireGuard config written to: {}", self.out_path.display());
        println!();
        println!("Next steps:");
        println!("  1. Generate key pair:  wg genkey | tee privatekey | wg pubkey > publickey");
        println!("  2. Paste the private key into the [Interface] PrivateKey field.");
        println!("  3. Send your public key to the server admin.");
        println!("  4. Install WireGuard and import the config:");
        println!("     macOS: brew install wireguard-tools && sudo wg-quick up {}", self.out_path.display());
        println!("     Linux: sudo wg-quick up {}", self.out_path.display());
        Ok(())
    }
}

// ── Shadowsocks (bonus) ───────────────────────────────────────────────────────

pub struct ShadowsocksConfig {
    pub server:   String,
    pub port:     u16,
    pub password: String,
    pub method:   String,
    pub out_path: PathBuf,
}

impl ShadowsocksConfig {
    pub fn write(&self) -> Result<()> {
        if self.password.is_empty() {
            bail!("Shadowsocks password cannot be empty");
        }
        let config = format!(r#"{{
    "server":      "{server}",
    "server_port": {port},
    "password":    "{password}",
    "method":      "{method}",
    "local_address": "127.0.0.1",
    "local_port":  1080,
    "timeout":     300,
    "fast_open":   false
}}
"#,
            server   = self.server,
            port     = self.port,
            password = self.password,
            method   = self.method,
        );
        fs::write(&self.out_path, config)?;
        println!("Shadowsocks config written to: {}", self.out_path.display());
        println!("Run: sslocal -c {}", self.out_path.display());
        Ok(())
    }
}
